version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    ignore:
      - dependency-name: "com.gradleup.shadow"
    groups:
      gradle:
        patterns:
          - "*"