apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-skattekort-person
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-skattekort-person-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-skattekort-person"} == 0
          for: 5m
          annotations:
            action: "Sjekk hvorfor applikasjonen er nede"
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Applikasjonen har restartet flere ganger de siste 5 minuttene!
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sokos-skattekort-person"}[5m])) by (container) > 2
          for: 5m
          annotations:
            action: "Sjekk hvorfor applikasjonen ikke klarer å restarte"
            summary: "App {{ $labels.container }} restarter mange ganger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Applikasjonen logger høy andel errors
          expr:
            'sum(max_over_time(log_messages_errors{namespace="okonomi",app="sokos-skattekort-person",level="Error"}[15m])
              or vector(0)) -
              sum(max_over_time(log_messages_errors{namespace="okonomi",app="sokos-skattekort-person",level="Error"}[15m]
              offset 15m) or vector(0)) > 5'
          for: 5m
          annotations:
            action: "<https://logs.adeo.no/app/discover#/?_g=(time:(from:now-1d,to:now))&_a=(filters:!((query:(match_phrase:(application:'sokos-skattekort-person'))),(query:(match_phrase:(cluster:'dev-fss'))),(query:(match_phrase:(level:'Warning')))))|Sjekk loggene>"
            summary: "`kubectl logs -l app=sokos-skattekort-person -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Applikasjonen logger høy andel warnings
          expr:
            'sum(max_over_time(log_messages_errors{namespace="okonomi",app="sokos-skattekort-person",level="Warning"}[15m])
              or vector(0)) -
              sum(max_over_time(log_messages_errors{namespace="okonomi",app="sokos-skattekort-person",level="Warning"}[15m]
              offset 15m) or vector(0)) > 5'
          for: 5m
          annotations:
            action: "<https://logs.adeo.no/app/discover#/?_g=(time:(from:now-1d,to:now))&_a=(filters:!((query:(match_phrase:(application:'sokos-skattekort-person'))),(query:(match_phrase:(cluster:'dev-fss'))),(query:(match_phrase:(level:'Warning')))))|Sjekk loggene>"
            summary: "`kubectl logs -l app=sokos-skattekort-person -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: warning
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"5.*", app="sokos-skattekort-person"}[3m])) > 2
          for: 5m
          annotations:
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`.
                      <https://logs.adeo.no/app/discover#/?_g=(time:(from:now-1d,to:now))&_a=(filters:!((query:(match_phrase:(application:'sokos-skattekort-person'))),(query:(match_phrase:(cluster:'dev-fss'))),(query:(match_phrase:(level:'Warning')))))|Sjekk loggene> for å se hvorfor dette feiler."
            action:  "`kubectl logs -l app=sokos-skattekort-person -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"4.*", status!~"404", app="sokos-skattekort-person"}[3m])) > 2
          for: 5m
          annotations:
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`. 
                       <https://logs.adeo.no/app/discover#/?_g=(time:(from:now-1d,to:now))&_a=(filters:!((query:(match_phrase:(application:'sokos-skattekort-person'))),(query:(match_phrase:(cluster:'dev-fss'))),(query:(match_phrase:(level:'Warning')))))|
                       Sjekk loggene> for å se hvorfor dette feiler."
            action: "`kubectl logs -l app=sokos-skattekort-person -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-skattekort-person-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-skattekort-person-slack
spec:
  receivers:
    - name: sokos-skattekort-person-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-dev'
          iconEmoji: ':alert:'
          username: 'Alert dev-fss'
          sendResolved: true
          httpConfig:
            proxyURL: http://webproxy.nais:8088
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_skattekort_person_type"
        matchType: "="
        value: "sokos-skattekort-person"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-skattekort-person-receiver
    repeatInterval: 5m
