apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-skattekort-person
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-skattekort-person-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="{{app}}"} == 0
          for: 5m
          annotations:
            action: "`kubectl describe pod {{ $labels.deployment }} -n {{ $labels.namespace }}` for events, og `kubectl logs -l {{ $labels.deployment }} -n {{ $labels.namespace }}` for logger"
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Høy andel error i logger
          expr: sum by (app, container, pod, namespace) (floor(increase(logback_events_total{app="{{app}}", level="error"} [3m]))) > 0
          for: 5m
          annotations:
            action: "`kubectl logs {{ $labels.pod }} -c {{ $labels.container }} -n {{ $labels.namespace }}`"
            summary: "Høy andel error i logger for app {{ $labels.app }} feiler med {{ $labels.exception }} i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Høy andel warning i logger
          expr: sum by (app, container, pod, namespace) (floor(increase(logback_events_total{app="{{app}}", level="warning"} [3m]))) > 0
          for: 5m
          annotations:
            action: "`kubectl logs {{ $labels.pod }} -c {{ $labels.container }} -n {{ $labels.namespace }}`"
            summary: "Høy andel error i logger for app {{ $labels.app }} feiler med {{ $labels.exception }} i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: warning
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"5.*", app="{{app}}"}[3m])) > 1
          for: 1m
          annotations:
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`.\n
                    Grunn:\n ```{{ $labels.problem_details }}```\n
                    Sjekk loggene for å se hvorfor dette feiler."
            action: "`kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}`"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom

        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"4.*", status!~"404", app="{{app}}"}[3m])) > 0
          for: 1m
          annotations:
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`.\n
                    Grunn:\n ```{{ $labels.problem_details }}```\n
                    Sjekk loggene for å se hvorfor dette feiler"
            action: "`kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}`"
          labels:
            namespace: okonomi
            severity: danger
            sokos_skattekort_person_type: sokos-skattekort-person
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-skattekort-person-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-skattekort-person-slack
spec:
  receivers:
    - name: sokos-skattekort-person-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-dev' # Endres til #team-mob-alerts-prod når applikasjonen prodsettes
          iconEmoji: ':alert:'
          username: Alert ({{ cluster }})
          sendResolved: true
          httpConfig:
            proxyURL: http://webproxy.nais:8088
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts -}}
            *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
            *Description:* {{ .Annotations.description }}
            *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
            {{ end }}
          color: |-
            {{ if eq .Status "firing" -}}
              {{ if eq .CommonLabels.severity "warning" -}}
                warning
              {{- else if eq .CommonLabels.severity "fatal" -}}
                #611f69
              {{- else if eq .CommonLabels.severity "critical" -}}
                #611f69
              {{- else if eq .CommonLabels.severity "danger" -}}
                danger
              {{- else if eq .CommonLabels.severity "error" -}}
                danger
              {{- else if eq .CommonLabels.severity "notice" -}}
                good
              {{- else if eq .CommonLabels.severity "info" -}}
                #36c5f0
              {{- else -}}
                .CommonLabels.severity
              {{- end -}}
            {{ else -}}
            good
            {{- end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_skattekort_person_type"
        matchType: "="
        value: "sokos-skattekort-person"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-skattekort-person-receiver
    repeatInterval: 2m
