apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      cpu: 2000m
      memory: 3072Mi
    requests:
      cpu: 80m
      memory: 1536Mi
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  webproxy: true
  accessPolicy:
    inbound:
      rules:
        - application: sokos-authentication-testapp
          cluster: dev-fss
          namespace: okonomi
  env:
    - name: USE_AUTHENTICATION
      value: "true"
