apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-skattekort-person
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-skattekort-person.intern.dev.nav.no
    - https://sokos-skattekort-person.dev-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: sokos-utbetalingsportalen
          namespace: okonomi
          cluster: dev-gcp
        - application: saas-proxy
          namespace: teamcrm
          cluster: dev-gcp
  webproxy: true
  vault:
    enabled: true
  envFrom:
    - secret: sokos-skattekort-person-oseskatt-q1-credentials
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # Oracle OS-eskatt
    - name: DATABASE_HOST
      value: dmv07-scan.adeo.no
    - name: DATABASE_PORT
      value: "1521"
    - name: DATABASE_NAME
      value: oseskatt_q1_ha
    - name: DATABASE_SCHEMA
      value: OSESKATT_Q1

    # PDL
    - name: PDL_URL
      value: https://pdl-api.dev.intern.nav.no/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default