name: Bygg, test og deploy til dev/prod

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.github/workflows/build-pr.yaml'
      - '.github/workflows/security.yaml'
      - '.github/workflows/alerts.yaml'
      - '.nais/alerts.yaml'

jobs:
  bygg-test-push-image:
    permissions:
      contents: "read"
      id-token: "write"
    name: Bygg/test og push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache gradle artifakter
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Bygg og test shadowJar
        run: ./gradlew test shadowJar
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}

      - name: Bygg docker image
        uses: docker/setup-buildx-action@v2

      - name: Push docker image til Google Artifact Registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev-fss:
    name: Deploy til dev-fss
    needs: bygg-test-push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          IMAGE: ${{ needs.bygg-test-push-image.outputs.image }}
          RESOURCE: .nais/naiserator-dev.yaml

  deploy-prod-fss:
    name: Deploy til prod-fss
    needs: [ deploy-dev-fss, bygg-test-push-image ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          IMAGE: ${{ needs.bygg-test-push-image.outputs.image }}
          RESOURCE: .nais/naiserator-prod.yaml