name: Deploy til dev og prod

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Bygg og push Docker image"]
    types:
      - completed

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  deploy-dev-fss:
    name: Deploy til dev-fss
    if: github.event.workflow_run.conclusion == 'success' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: .nais/naiserator-dev.yaml

#  deploy-prod-fss:
#    name: Deploy til prod-fss
#    needs: deploy-dev-fss
#    if: github.ref == 'refs/heads/master'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
#          CLUSTER: dev-fss
#          RESOURCE: .nais/naiserator-prod.yaml

  reportFailure:
    name: Slack notifikasjon bygg feiler
    needs: [ deploy-dev-fss ]
    # needs: [ deploy-dev-fss, deploy-dev-fss ]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sender notifikasjon til Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: team-mob-workflow
          SLACK_COLOR: '#ff0000'
          SLACK_ICON: https://user-images.githubusercontent.com/29889280/178134303-4556873f-b2d6-46a0-b5af-a587b0fabb96.png
          SLACK_TITLE: ${{ github.repository }}
          SLACK_MESSAGE: 'Deploy til dev og prod feilet! :ghost:'
          SLACK_USERNAME: workflowBot
          MSG_MINIMAL: actions url,commit
          SLACK_FOOTER: 'team-mob'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}