name: Deploy application

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.editorconfig'
      - 'setupLocalEnvironment.sh'
      - 'dokumentasjon/**'
      - '.github/workflows/build-pr.yaml'
      - '.github/workflows/codeql-trivy-scan.yaml'
      - '.github/workflows/manual-deploy.yaml'
      - '.github/dependabot.yaml'
env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"
  deployments: "write"
  pull-requests: "write"

jobs:
  run-application-tests:
    name: Run application tests
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-run-test.yaml@main

  assemble-build-push-image-dev:
    needs: [ run-application-tests ]
    name: Assemble application & build/push dev image
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-assemble-build-push-image.yaml@main
    secrets: inherit
    with:
      image-suffix: 'dev'
      dockerfile: './.nais/dev/Dockerfile'

  assemble-build-push-image-prod:
    needs: [ run-application-tests ]
    name: Assemble application & build/push prod image
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-assemble-build-push-image.yaml@main
    secrets: inherit
    with:
      dockerfile: './.nais/prod/Dockerfile'

  deploy-dev:
    needs: [ assemble-build-push-image-dev ]
    name: Deploy to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/dev/naiserator-dev.yaml
      image: ${{ needs.assemble-build-push-image-dev.outputs.image }}

  deploy-prod:
    needs: [ assemble-build-push-image-prod, deploy-dev ]
    name: Deploy to prod-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: prod-fss
      resource: .nais/prod/naiserator-prod.yaml
      image: ${{ needs.assemble-build-push-image-prod.outputs.image }}