name: Deploy application manually

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        options:
          - dev

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  run-application-tests:
    name: Run tests
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-run-test.yaml@main

  assemble-build-push-image-dev:
    needs: [ run-application-tests ]
    name: Assemble application & build/push image dev
    uses: navikt/mob-gha-workflows/.github/workflows/gradle-assemble-build-push-image.yaml@main
    secrets: inherit
    with:
      image-suffix: 'dev'
      image-tag: 'snapshot'
      dockerfile: './.nais/dev/Dockerfile'

  deploy-dev:
    needs: [ assemble-build-push-image-dev ]
    name: Deploy to dev-fss
    uses: navikt/mob-gha-workflows/.github/workflows/nais-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/dev/naiserator-dev.yaml
      image: ${{ needs.assemble-build-push-image-dev.outputs.image }}